In [1]:
# Importing Libraries

import pandas as pd
import numpy as np
import os
import requests
import json
from datetime import datetime

In [2]:
# Set the path to the main directory containing subfolders
folderpath = '/Users/vineetasinha/Documents/workspace/NYCitiBike/Data-Q1'
print(f"Base directory path: {folderpath}")

contents = os.listdir(folderpath)
print("Contents of the directory:")
for item in contents:
    print(item)
    
# Create a list to store DataFrames
FirstQuater = []

# Iterate through each subfolder in the base directory
for subfolder in os.listdir(folderpath):
    subfolder_path = os.path.join(folderpath, subfolder)
    
    # Ensure the subfolder path is a directory
    if os.path.isdir(subfolder_path):
        
        # List all CSV files in the subfolder
        csv_files = [f for f in os.listdir(subfolder_path) if f.endswith('.csv')]
        
        # Read each CSV file and append to the list
        for file in csv_files:
            file_path = os.path.join(subfolder_path, file)
            df = pd.read_csv(file_path)
            FirstQuater.append(df)

# Concatenate all DataFrames into a single DataFrame
Bike_Q1 = pd.concat(FirstQuater, ignore_index=True)

# Display the first few rows of the combined DataFrame
Bike_Q1.head()

Base directory path: /Users/vineetasinha/Documents/workspace/NYCitiBike/Data-Q1
Contents of the directory:
.DS_Store
202202-citibike-tripdata
202203-citibike-tripdata
202201-citibike-tripdata
202204-citibike-tripdata

/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/383567147.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,70F3BA79664016C1,classic_bike,2022-02-28 09:22:49.821,2022-02-28 09:28:55.174,9 Ave & W 18 St,6190.08,Greenwich Ave & Charles St,5914.08,40.743174,-74.003664,40.735238,-74.000271,member
1,8FA3412A958122D0,electric_bike,2022-02-14 10:47:30.462,2022-02-14 10:56:04.433,W 120 St & Claremont Ave,7745.07,Frederick Douglass Blvd & W 117 St,7688.12,40.810949,-73.963400,40.805159,-73.954692,member
2,0E2BA02AEAD03EB8,electric_bike,2022-02-18 22:26:55.796,2022-02-18 22:44:31.472,E 4 St & 2 Ave,5593.04,Greenwich Ave & Charles St,5914.08,40.726281,-73.989780,40.735238,-74.000271,member
3,B626F8E1D7ABABBA,classic_bike,2022-02-09 18:38:18.621,2022-02-09 18:47:11.274,White St & Johnson Ave,5099.03,Irving Ave & Harman St,4856.05,40.707174,-73.935810,40.701080,-73.917900,member
4,605E7CC493D08F3B,electric_bike,2022-02-06 14:52:48.564,2022-02-06 14:55:56.218,S Portland Ave & Hanson Pl,4354.05,Nevins St & Schermerhorn St,4437.09,40.685396,-73.974315,40.687372,-73.981761,member

In [3]:
# Set the path to the main directory containing subfolders
folderpath = '/Users/vineetasinha/Documents/workspace/NYCitiBike/Data-Q2'
print(f"Base directory path: {folderpath}")

contents = os.listdir(folderpath)
print("Contents of the directory:")
for item in contents:
    print(item)
    
# Create a list to store DataFrames
SecondQuarter = []

# Iterate through each subfolder in the base directory
for subfolder in os.listdir(folderpath):
    subfolder_path = os.path.join(folderpath, subfolder)
    
    # Ensure the subfolder path is a directory
    if os.path.isdir(subfolder_path):
        
        # List all CSV files in the subfolder
        csv_files = [f for f in os.listdir(subfolder_path) if f.endswith('.csv')]
        
        # Read each CSV file and append to the list
        for file in csv_files:
            file_path = os.path.join(subfolder_path, file)
            df = pd.read_csv(file_path)
            SecondQuarter.append(df)

# Concatenate all DataFrames into a single DataFrame
Bike_Q2 = pd.concat(SecondQuarter, ignore_index=True)

# Display the first few rows of the combined DataFrame
Bike_Q2.head()

Base directory path: /Users/vineetasinha/Documents/workspace/NYCitiBike/Data-Q2
Contents of the directory:
202208-citibike-tripdata
.DS_Store
202207-citibike-tripdata
202206-citibike-tripdata
202205-citibike-tripdata

/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/2337406943.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member

In [4]:
# Set the path to the main directory containing subfolders
folderpath = '/Users/vineetasinha/Documents/workspace/NYCitiBike/Data-Q3'
print(f"Base directory path: {folderpath}")

contents = os.listdir(folderpath)
print("Contents of the directory:")
for item in contents:
    print(item)
    
# Create a list to store DataFrames
ThirdQuarter = []

# Iterate through each subfolder in the base directory
for subfolder in os.listdir(folderpath):
    subfolder_path = os.path.join(folderpath, subfolder)
    
    # Ensure the subfolder path is a directory
    if os.path.isdir(subfolder_path):
        
        # List all CSV files in the subfolder
        csv_files = [f for f in os.listdir(subfolder_path) if f.endswith('.csv')]
        
        # Read each CSV file and append to the list
        for file in csv_files:
            file_path = os.path.join(subfolder_path, file)
            df = pd.read_csv(file_path)
            ThirdQuarter.append(df)

# Concatenate all DataFrames into a single DataFrame
Bike_Q3 = pd.concat(ThirdQuarter, ignore_index=True)

# Display the first few rows of the combined DataFrame
Bike_Q2.head()

Base directory path: /Users/vineetasinha/Documents/workspace/NYCitiBike/Data-Q3
Contents of the directory:
202211-citibike-tripdata
.DS_Store
202210-citibike-tripdata
202209-citibike-tripdata
202212-citibike-tripdata

/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)
/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/32940961.py:26: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member

In [5]:
Bike_Q2.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member

I distributed the data for year 2022 in three quarters as Bike_Q1, Bike_Q2 & Bike_Q3 respectively. The code I wrote is designed to read and combine CSV files from multiple subfolders within a specified directory. It first verifies that the main directory exists and lists its contents. It then iterates through each subfolder, checking if it's a directory and identifying CSV files within it. Each CSV file is read into a DataFrame and appended to a list. After collecting all DataFrames, the code concatenates them into a single DataFrame and displays a preview of the combined data. This approach efficiently consolidates data from multiple sources into one comprehensive dataset.

In [6]:
# Define your NOAA token

Token = 'RQKdsDofOqzjBbzdvBYFrQdxPNBfBqei'

In [7]:
r = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TAVG&limit=1000&stationid=GHCND:USW00014732&startdate=2022-01-01&enddate=2022-12-31', headers={'token':Token})

# Load the api response as a json

d = json.loads(r.text)

In [8]:
# Secure all items in the response that correspond to TAVG

avg_temps = [item for item in d['results'] if item['datatype']=='TAVG']
# Get only the date field from all average temperature readings

data_temp = [item['date'] for item in avg_temps]
# Get the temperature from all average temperature readings

temps = [item['value'] for item in avg_temps]

In [9]:
#df_temp = pd.DataFrame()

#df_temp['date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in data_temp]

In [10]:
# Put the results in a dataframe

df_temps = pd.DataFrame()
# Get only date and case it to date time; convert temperature from tenths of celsius to normal celsius

df_temps['Date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in data_temp] 
df_temps['AvgTemp'] = [float(v)/10.0 for v in temps]

df_temps.tail()

          Date  AvgTemp
360 2022-12-27     -0.7
361 2022-12-28      3.4
362 2022-12-29      6.4
363 2022-12-30      9.3
364 2022-12-31      8.2

In [11]:
#df_temps.head()
df_temps['Date'] = pd.to_datetime(df_temps['Date'])
df_temps.head()

        Date  AvgTemp
0 2022-01-01     11.6
1 2022-01-02     11.4
2 2022-01-03      1.4
3 2022-01-04     -2.7
4 2022-01-05      3.2

In [12]:

Bike_Q2['started_at'] = pd.to_datetime(Bike_Q2['started_at'], dayfirst = True)
Bike_Q2['Date'] = pd.to_datetime(Bike_Q2['started_at'], format='%Y-%m-%d %H:%M:%S.%f').dt.normalize()

/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/3349243827.py:1: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S.%f format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  Bike_Q2['started_at'] = pd.to_datetime(Bike_Q2['started_at'], dayfirst = True)

In [13]:
Bike_Q2.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Date
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual,2022-08-27
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual,2022-08-20
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member,2022-08-31
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member,2022-08-02
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member,2022-08-25

In [14]:
print(Bike_Q2.dtypes)

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at                      object
start_station_name            object
start_station_id              object
end_station_name              object
end_station_id                object
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
Date                  datetime64[ns]
dtype: object

In [15]:
%%time
df_Bike_Q2 = Bike_Q2.merge(df_temps, how = 'left', on = 'Date', indicator = True)

CPU times: user 7.48 s, sys: 9.34 s, total: 16.8 s
Wall time: 20.8 s

In [16]:
print(df_temps.dtypes)

Date       datetime64[ns]
AvgTemp           float64
dtype: object

In [17]:
df_Bike_Q2['_merge'].value_counts(dropna = False)

_merge
both          13183284
left_only            7
right_only           0
Name: count, dtype: int64

In [18]:
df_Bike_Q2.head(5)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,Date,AvgTemp,_merge
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual,2022-08-27,27.8,both
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual,2022-08-20,27.9,both
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member,2022-08-31,25.6,both
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member,2022-08-02,26.4,both
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member,2022-08-25,28.1,both

In [19]:
Bike_Q1['started_at'] = pd.to_datetime(Bike_Q1['started_at'], dayfirst = True)
Bike_Q1['Date'] = pd.to_datetime(Bike_Q1['started_at'], format='%Y-%m-%d %H:%M:%S.%f').dt.normalize()

/var/folders/pz/jfzwtwys2cb42xz8n922cq7h0000gn/T/ipykernel_46153/3867035129.py:1: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S.%f format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  Bike_Q1['started_at'] = pd.to_datetime(Bike_Q1['started_at'], dayfirst = True)

In [20]:
%%time
df_Bike_Q1 = Bike_Q1.merge(df_temps, how = 'left', on = 'Date', indicator = True)

CPU times: user 3.56 s, sys: 4.26 s, total: 7.83 s
Wall time: 11.2 s

In [21]:
df_Bike_Q2['_merge'].value_counts(dropna = False)

_merge
both          13183284
left_only            7
right_only           0
Name: count, dtype: int64

In [22]:
Bike_Q3['started_at'] = pd.to_datetime(Bike_Q3['started_at'], dayfirst = True, errors='coerce')
Bike_Q3['Date'] = pd.to_datetime(Bike_Q3['started_at'], format='%Y-%m-%d %H:%M:%S.%f').dt.normalize()

In [23]:
%%time
df_Bike_Q3 = Bike_Q3.merge(df_temps, how = 'left', on = 'Date', indicator = True)

CPU times: user 6.16 s, sys: 8.82 s, total: 15 s
Wall time: 19.2 s

In [24]:
df_Bike_Q2['_merge'].value_counts(dropna = False)

_merge
both          13183284
left_only            7
right_only           0
Name: count, dtype: int64

In [28]:
# Exporting the dataset to csv file

df_Bike_Q1.to_csv('/Users/vineetasinha/Documents/workspace/NYbike_trips_Q1.csv', index=False)
df_Bike_Q2.to_csv('/Users/vineetasinha/Documents/workspace/NYbike_trips_Q2.csv', index=False)
df_Bike_Q3.to_csv('/Users/vineetasinha/Documents/workspace/NYbike_trips_Q3.csv', index=False)